name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_PLAYWRIGHT: true

jobs:
  test-build-deploy:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Run unit tests
        run: npm test

      - name: Install Playwright Browsers
        if: ${{ !env.SKIP_PLAYWRIGHT }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ !env.SKIP_PLAYWRIGHT }}
        run: npm run test:e2e

      - name: Build application
        if: ${{ success() }}
        continue-on-error: true
        run: npm run build

      - name: Notify Discord of failed build
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ failure() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          color: '#a61e1eff'
          title: 'Pokedex build failed :x:'
          description: 'Build failed on commit ${{ github.sha }} by ${{ github.actor }}.'
          footer: 'This is an automated message'

      - name: Upload build artifact
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/

  tag_and_release:
    needs: [test-build-deploy]
    name: Deploy and Tag Release
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: dump commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist

      - name: Deploy to Azure Web App (on push to main)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mats-pokedex'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          slot-name: 'Production'
          package: dist

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'

      - name: Debug webhook
        run: |
          echo "Length: ${#DISCORD_WEBHOOK}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          username: 'Pokedex'
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: 'Pokedex deployment'
          embed-description: 'A new version of the Pokedex has been deployed :tada:'
          embed-color: 5763719
          embed-author-name: ${{ github.actor }}
